# This is similar to docker-compose.yml, but with all the component services running
# in development mode, with their source code mounted as volumes within the docker
# containers, so that changes are applied in realtime, without requiring a rebuild &
# restart cycle.
version: '2'
services:
  fees-dev:
    # https://github.com/ministryofjustice/tax-tribunals-fees
    build:
      context: tax-tribunals-fees/
      dockerfile: Dockerfile.development
    env_file: .env.fees-dev
    links:
      - fees-db:db
    ports:
      - "4000:3000"
    volumes:
      - ./tax-tribunals-fees:/usr/src/app
      - ./logs/fees:/usr/src/app/log
  fees-db:
    image: postgres

  datacapture-dev:
    # https://github.com/ministryofjustice/tax-tribunals-datacapture
    build:
      context: tax-tribunals-datacapture/
      dockerfile: Dockerfile.development
    env_file: .env.datacapture-dev
    links:
      - datacapture-db:db
      - fees-dev
      - uploader
    ports:
      - "3000:3000"
    volumes:
      - ./tax-tribunals-datacapture:/usr/src/app
      - ./logs/datacapture:/usr/src/app/log
  datacapture-db:
    image: postgres

  # Uploader API
  uploader:
    # https://github.com/ministryofjustice/mojfile-uploader
    build: mojfile-uploader
    entrypoint: puma
    env_file: .env.mojfile-uploader
    volumes:
      - ./mojfile-uploader/run.sh:/usr/src/app/run.sh
    ports:
      - "9292:9292"
    links:
      - clamav-rest
  clamav:
    # https://github.com/ministryofjustice/moj-clamav-daemon
    image: registry.service.dsd.io/ministryofjustice/clamav:0.1.0
  clamav-rest:
    # https://github.com/ministryofjustice/moj-clamav-rest
    image: registry.service.dsd.io/ministryofjustice/clamav-rest:0.1.0
    links:
      - clamav:clamav-server
    environment:
      HOST: clamav-server
      PORT: 3310
    depends_on:
      - clamav
    ports:
      - 8080:8080
